---
title: "Introduction to Open Data Science 2022 - Course Diary"
author: "Jaana Kuoppala"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 2
    fig_caption: true
    fig_width: 6
    fig_height: 4
---

------------------------------------------------------------------------

# Getting started

```{r child = "chapter1.Rmd"}
# This will include Chapter 1 (that is updated in its own file) in the document.
```

------------------------------------------------------------------------

# Regression and model validation

```{r child = "chapter2.Rmd"}
# This will include Chapter 2 (that is updated in its own file) in the document.
```

------------------------------------------------------------------------

# Logistic regression

```{r child = "chapter3.Rmd"}
# This will include Chapter 3 (that is updated in its own file) in the document.
```

------------------------------------------------------------------------

# Clustering and classification

```{r child = "chapter4.Rmd"}
# This will include Chapter 4 (that is updated in its own file) in the document.
```

------------------------------------------------------------------------

# Dimensionality reduction techniques

```{r child = "chapter5.Rmd"}
# This will include Chapter 5 (that is updated in its own file) in the document.
```

------------------------------------------------------------------------



